services:
  backend:
    build:
      context: ../
      dockerfile: web/Dockerfile
    container_name: backend
    restart: always
    environment:
      - FLASK_DEBUG=0
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_common.conf:/etc/nginx/snippets/proxy_common.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./letsencrypt_data:/etc/letsencrypt
      - ./certbot_webroot:/var/www/certbot
    entrypoint: |
      sh -c '
        trap exit TERM;
        while :; do
          echo "Certbot: Attempting to renew certificates...";
          certbot renew --webroot -w /var/www/certbot --quiet;
          echo "Certbot: Next renewal check in 48 hours.";
          sleep 48h & wait $${!}; # Wait for 48 hours or until TERM signal
        done;
      '
    depends_on:
      - nginx
