services:
  backend:
    build:
      context: ../
      dockerfile: web/Dockerfile
    container_name: unicode-detector-backend
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=0
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]

  nginx:
    image: nginx:stable-alpine
    container_name: unicode-detector-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - backend
