services:
  backend:
    build:
      context: ../
      dockerfile: web/Dockerfile
    container_name: backend
    restart: always
    environment:
      - FLASK_DEBUG=0
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_common.conf:/etc/nginx/snippets/proxy_common.conf:ro
      - /var/certbot/conf:/etc/letsencrypt:ro
      - /var/certbot/www:/var/www/certbot:ro
    depends_on:
      - backend
